# azure-pipelines.yml

trigger:
  branches:
    include:
      - main  # Triggers the pipeline when changes are pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu VM to run the pipeline (can be 'windows-latest', 'macos-latest', etc.)

variables:
  buildConfiguration: 'Release'  # Default build configuration, can be overridden

steps:
- task: UseDotNet@2  # Example: Install .NET SDK (adjust this based on your project)
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Specify your desired .NET SDK version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: Restore@1  # Restore dependencies (for .NET, adjust for other projects)
  inputs:
    restoreSolution: '**/*.sln'

- task: Build@1  # Build the project
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:Configuration=$(buildConfiguration)'

- task: Publish@1  # Publish build artifacts
  inputs:
    publishWebProjects: false
    buildPlatform: '$(BuildPlatform)'
    buildConfiguration: '$(BuildConfiguration)'

- task: CopyFiles@2  # Example step to copy files
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/published'

- task: PublishBuildArtifacts@1  # Publish the build artifact
  inputs:
    ArtifactName: 'drop'
    publishLocation: 'Container'
